services:
  xiaozhi-client-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: xiaozhi-client:dev
    container_name: xiaozhi-client-dev
    restart: unless-stopped

    # 端口映射
    ports:
      - "9999:9999"  # Web UI 端口
      - "3000:3000"  # 备用端口

    # 环境变量
    environment:
      - NODE_ENV=development
      - XIAOZHI_WORKSPACE=/workspace

    # 挂载卷 - 开发模式下挂载配置和自定义文件
    volumes:
      # 挂载自定义配置文件
      - ./xiaozhi.config.json:/workspace/xiaozhi.config.json:ro
      # 日志文件持久化
      - ./logs:/workspace/logs
      # 挂载自定义 MCP 服务器（开发时可修改）
      - ./mcpServers:/workspace/mcpServers
      # 挂载整个工作空间（开发模式）
      - ./workspace:/workspace

    # 健康检查
    healthcheck:
      test: ["CMD", "xiaozhi", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # 网络配置
    networks:
      - xiaozhi-dev-network

    # 开发环境不设置严格的资源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

    stdin_open: true
    tty: true

# 开发网络配置
networks:
  xiaozhi-dev-network:
    driver: bridge
